cache:
  directories:
  - $HOME/.m2
matrix:
  include:
  - os: linux
    dist: xenial
    language: java
    jdk: openjdk8
  - os: osx
    language: java
    osx_image: xcode10.1
notifications:
  email:
    - ben.alex@acegi.com.au
    - stoffe@gmail.com
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
install:
  - mvn -B -Pdeploy --settings .travis-settings.xml -V dependency:go-offline
script:
  - mvn -B -Pdeploy --settings .travis-settings.xml -Dgpg.skip=true verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then echo $GPG_KEY | base64 --decode | gpg --batch --fast-import -; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then mvn -B -Pdeploy --settings .travis-settings.xml deploy; fi
